### ISSUE TITLE
win_if_list does not show wan interface(s)

### ISSUE THREAD

**Issue by MikTur** [AlienCowEatCake/wpa_supplicant-windows#3]
Hi, have just deployed the wpa_supplicant suite by using mingw64.
Have recompiled openssl in order to have the whole linking to the correct openssl libraries and have adjusted the CMakeLists.txt in order to have a building scenario.
The gui frontend has been omitted as there are many issues with qt4 and mingw64.
When launched the win_if_list executable can find all the LAN adapters but no the WAN ones.
This is the output:
 ./win_if_list.exe
ifname: \Device\NPF_{CB5E9FA0-A4FC-4981-BF03-024ABF62A836}
description: TAP-Windows Adapter V9

ifname: \Device\NPF_{21BEC55A-2BF7-44B5-969F-1627A9530B8E}
description: Oracle

ifname: \Device\NPF_{B50A3368-9039-4B2D-BBED-130CE1AB954E}
description: Microsoft

ifname: \Device\NPF_{3401EF9C-D494-4380-B8D2-C84EFE4DD614}
description: Microsoft

ifname: \Device\NPF_{7074BF71-2BD9-4CFC-8EA9-2DCF7BC4A27D}
description: Realtek Ethernet Controller

The cmake command line command issued was:
cmake .. -G Ninja -DWPAS_CTRL_IFACE=pipe

All the binaries are linked correctly and no dependencies are lacking.
Thanks for any help.

**Comment by AlienCowEatCake** [comment]
Hi, can you provide info about your system and mingw64 version please?
If you are using Windows Vista or newer version, this port definitely should not work. NDIS driver interface in wpa_supplicant was abandoned long time ago, so research to adapt it for new systems is required

**Comment by MikTur** [comment]
Hi,
Thanks for the reply.
My host system is having windows 10 pro and mingw version 7.1.
At this moment I can not supply more information as I am on vacancy and I
will be back on the next Monday.
M.

**Comment by AlienCowEatCake** [comment]
It shouldn't work on Windows 10 even with MinGW. I think it could be adapted theoretically, but it is out of scope for this project
